name: CI

on:
  push:
    branches: ["main"]
  pull_request_target:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install dependencies
      run: uv sync --frozen

    - name: set locale
      run: |
        sudo locale-gen ja_JP.UTF-8
        sudo update-locale LANG=ja_JP.UTF-8

    - name: Download syukujitsu.csv
      run: curl -vvv -LO ${CSV_URL}
      env:
        CSV_URL: https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv

    - name: Execute
      run: uv run main.py
      env:
        TZ: "Asia/Tokyo"

    - name: Set Build parameter
      id: build-parameter
      run: |
        if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
          echo "is_production=false" >> $GITHUB_OUTPUT
        else
          echo "is_production=true" >> $GITHUB_OUTPUT
        fi

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v3.0
      with:
        alias: ${{ github.head_ref }}
        publish-dir: './dist'
        production-deploy: ${{ steps.build-parameter.outputs.is_production }}
        github-token: ${{ github.token }}
        enable-commit-comment: false
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
